MiSTer-devel/SNES_MiSTer

- src/PPU.vhd
Now Blargg's SNES OAM Test	 passes
> OAM write fix

- src/PPU.vhd
Fixes black bar on top of Super Punch-Out circuit winner screen
Fixes garbage on first line in Aladdin and Super Street Fighter 2 Zangief stage.
> Fixes for color window and OAM

- src/PPU.vhd
Vsync should be 3 lines instead of 4.
> Fix Vsync length

- src/PPU.vhd
- src/PPU_PKG.vhd
Change sprite evaluation to be closer to a real SNES.
Fixes Uniracer 2 player
> PPU: Change sprite evaluation

- src/65C816/P65C816.vhd
- src/CPU.vhd
- rework HV-IRQ interrupt (Top Gear 3000 new bug)
- correct WRAM refresh position
> SCPU fixes

- SNES.qsf
- SNES.sv
- cheatcodes.sv
- src/SNES.vhd
- src/main.v
I did my best with the VHDL but i'm less familiar with it, if you have a chance please make sure I'm not doing anything bad there.
Codes can be generated from the same place:
https://gamehacking.org/system/snes
Select MiSTer from the list.
> Add cheat code support

- src/PPU.vhd
> PPU: Hires subscreen color math should use the previous MAIN_COLOR

- src/PPU.vhd
Do color math on every half cycle with current and previous color.
Save MATH, HALF & SUB_MATH_EN on mainscreen pixel cycle only so they
will also be used for the following subscreen pixel cycle.
> PPU: Adjust color math

- README.md
- SNES_Turbo.md
this is my first time using github and i accidentally created multiple commits instead of bundling all in one.
i know how to avoid doing this in the future, but i cannot find a way to remedy today's mistake in their web based editor currently.  apologies for this.
> SNES Docs update & turbo mode test results/info page created

- sys/sys_top.v
Otherwise there is a missing Hsync at the end of Vsync.
I don't know if this should be handled in sys or the core should generate Csync. Every core should have Csync like this. Vsync needs to be aligned to Hsync.
This is a comparison between MiSTer and a real SNES:
> sys: Csync: Shift Hsync left by 1 Hsync period during Vsync

- src/CPU.vhd
should fix the issue in the demo of Chrono Trigger
> SCPU: fix joystick auto read mode

- src/DSP.vhd
- src/DSP_PKG.vhd
BRR_BUF and GTBL moved to BRAM: 40% size decrease with the expense of only 2 BRAM blocks.
Probably you can wait with the merge until it's tested by more than one people (me).
> DSP area optimization

- src/CPU.vhd
Please see commit message, fixes music in secret of mana and others.
> Additional turbo improvements

- src/PPU.vhd
There should be black borders around the stage in the beginning.
> Enable BG2 mode7 color math (Contra 3 stage 2 top view)

- src/PPU.vhd
M7_TEMP_X and M7_TEMP_Y are calculated for the next line but use
the current line count so Mode 7 is shifted down by 1 line.
This is visible in the Chrono trigger intro where you can see the
pendulum shift up 1 pixel when the text starts scrolling.
> Fix Mode 7 shifted down by 1 line

- SNES.sv
fix Super Metroid & A Link to the Past Combo Randomizer Beta
> BSRAM: fill with FF

- SNES.sv
- src/CPU.vhd
fix world map sequences in Illusion of Gaia
> SCPU: fix dma registers space

- SNES.sv
- rtl/lightgun.sv
Adding virtual Konami Justifier lightgun with reload button support.
> Adding initial virtual Justifier support for Lethal Enforcers.

- rtl/DSP.vhd
Resolves --> https://github.com/MiSTer-devel/SNES_MiSTer/issues/268
> Fix by @greyrogue for spc initial registers test rom

- SNES.sv
- files.qip
- rtl/miracle.sv
-Set the Miracle Piano option to yes to connect midilink to controller port 1, and move the first controller to SNES controller port 2.
> Add support for Miracle Piano

- SNES.sv
- Added SNAC auto detection.
- Moved mouse, piano, and joyswap to new menu - Input Options.
- Moved HW specific options to menu - Hardware.
> SNAC auto detect, organize OSD input options

- SNES.sv
- rtl/ioport.sv
Adds rumble support: https://github.com/LimitedRunGames-Tech/snes-rumble
Tested with the test roms and two current ROM hacks.
Resolves Issue: https://github.com/MiSTer-devel/SNES_MiSTer/issues/417
> Rumble Support
